blank_issues_enabled: false

contact_links:
  - name: Documentation
    url: https://github.com/Sentinel-Security-Management/sentinel-agent/blob/main/README.md
    about: Read the documentation before opening an issue.

  - name: Discussions
    url: https://github.com/Sentinel-Security-Management/sentinel-agent/discussions
    about: Ask questions and discuss ideas with the community.